### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hernanytec** [hernanytec/instruct-challenge#1]
- [x] Criar e configurar projeto React
- [x] Criar estrutura básica do card
- [x] Receber dados do endpoint
- [x] Listar todos os dados nos cards
- [x] Criar searchbar na interface
- [x] Implementar a filtragem pelo email
- [x] Aprimorar UI/UX
